language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: vinodanandan-github
    token:
      secure: $SONAR_TOKEN_PITEST

jdk:
  - oraclejdk8
script: 
  - mvn clean package sonar:sonar

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache  
