language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: vinodanandan-github
    token:
      secure: $SONAR_TOKEN_PITEST

jdk:
  - oraclejdk8
script: ./travis.sh
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache  
      
before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;